import { test, beforeEach } from 'node:test';
import assert from 'node:assert/strict';
import { createTestDb, setDb } from '../src/db/index.ts';
import { register } from '../src/auth/service.ts';
import { getProduct, listMovements } from '../src/inventory/service.ts';
import { FakeProvider, type NotaFiscalProvider } from '../src/nfe/provider.ts';
import {
  confirmImport,
  getMovementSource,
  previewFromAccessKey,
} from '../src/nfe/import-service.ts';
import { AppError } from '../src/errors.ts';

const KEY = '43240612345678901234567890123456789012345678';

let userId: number;
let provider: NotaFiscalProvider;

beforeEach(() => {
  setDb(createTestDb());
  userId = register('imp@example.com', 'segredo123').id;
  provider = new FakeProvider({
    [KEY]: {
      accessKey: KEY,
      issuedAt: '2024-06-01T10:00:00-03:00',
      items: [
        { description: 'ARROZ 5KG', gtin: '789', quantity: 2, unit: 'UN', unitValue: 25.9 },
        { description: 'FEIJAO 1KG', gtin: null, quantity: 3, unit: 'UN', unitValue: 8.5 },
      ],
    },
  });
});

test('preview returns items without changing stock', async () => {
  const preview = await previewFromAccessKey(userId, KEY, provider, 'sefaz');
  assert.equal(preview.items.length, 2);
  assert.equal(preview.alreadyImported, false);
});

test('confirm imports items and increases balances', async () => {
  const preview = await previewFromAccessKey(userId, KEY, provider, 'sefaz');
  const result = confirmImport(userId, {
    accessKey: preview.accessKey,
    issuedAt: preview.issuedAt,
    source: 'sefaz',
    items: preview.items,
  });
  assert.equal(result.itemsImported, 2);
  assert.equal(result.productsCreated, 2);
});

test('re-importing the same note is blocked', async () => {
  const preview = await previewFromAccessKey(userId, KEY, provider, 'sefaz');
  confirmImport(userId, { accessKey: KEY, source: 'sefaz', items: preview.items });
  assert.throws(
    () => confirmImport(userId, { accessKey: KEY, source: 'sefaz', items: preview.items }),
    (e: AppError) => e.code === 'note_already_imported',
  );
});

test('traceability links movement back to source note', async () => {
  const preview = await previewFromAccessKey(userId, KEY, provider, 'sefaz');
  const { noteId } = confirmImport(userId, { accessKey: KEY, source: 'sefaz', items: preview.items });
  // find a movement generated by the import
  const anyProduct = getProduct(userId, 1);
  const mv = listMovements(userId, anyProduct.id)[0];
  const trace = getMovementSource(userId, mv.id);
  assert.equal(trace.note?.id, noteId);
  assert.equal(trace.note?.accessKey, KEY);
});

test('source failure (SEFAZ down) does not change stock; manual confirm still works', async () => {
  const failing: NotaFiscalProvider = {
    async fetchByAccessKey() {
      throw new AppError(503, 'sefaz_unavailable', 'fora do ar');
    },
  };
  await assert.rejects(
    () => previewFromAccessKey(userId, KEY, failing, 'sefaz'),
    (e: AppError) => e.code === 'sefaz_unavailable',
  );
  // Manual entry path: user types the items, still keyed by the scanned access key.
  const result = confirmImport(userId, {
    accessKey: KEY,
    source: 'manual',
    items: [{ description: 'ITEM MANUAL', quantity: 4, unit: 'UN' }],
  });
  assert.equal(result.itemsImported, 1);
});

test('empty note is rejected on confirm', () => {
  assert.throws(
    () => confirmImport(userId, { accessKey: KEY, source: 'manual', items: [] }),
    (e: AppError) => e.code === 'empty_note',
  );
});
